services:
  - type: web
    name: bytelearn-backend
    env: python
    region: oregon
    buildCommand: "./backend/build.sh"
    startCommand: "cd backend && gunicorn base.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DATABASE_URL
        fromDatabase:
          name: bytelearn-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
